title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I post about stuff I do, big and small. Probably mostly coding and config.

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
