title: Projects and ponderings
author: Filip Marko
description: >
  This is where I post about stuff I do, big and small. Probably mostly coding and config.

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
